baseUrl: "https://clinquant-druid-c44612.netlify.app/"
languageCode: en-us
title: Brandshaw.cloud
theme: PaperMod
googleAnalytics: G-1234567890


disqusShortname: yourDisqusShortname

params: 
   fuseOpts:
      isCaseSensitive: false
      shouldSort: true
      location: 0
      distance: 1000
      threshold: 0.4
      minMatchCharLength: 0
      keys: ["title", "permalink", "summary", "content"]

params: 
  homeInfoParams:
    Title: "Hi I am John Bradshaw"
    Content: Head of Cloud Hub for @wpp, building out cloud for WPP and our OpCo’s in a customer obsessed way!
  socialIcons:
    - name: linkedin
      url: "https://facebook.com/"
    - name: twitter
      url: "https://twitter.com/"

  cover: 
    linkFullImages: true

  backgroundImage: img/waterbottle.jpg
  
  # ShowBreadCrumbs: true

  ShowReadingTime: true

  ShowPostNavLinks: true

  ShowShareButtons: true

  comments: true


 

menu: 
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 20
    - identifier: search
      name: Search
      url: /search/
      weight: 30

outputs:
  home:
      - HTML
      - RSS
      - JSON # is necessary