baseUrl: ""
languageCode: en-us
title: My Hugo Site
theme: PaperMod

params: 
  homeInfoParams:
    Title: "Hi I am John Bradshaw"
    Content: Head of Cloud Hub for @wpp, building out cloud for WPP and our OpCo’s in a customer obsessed way!
  socialIcons:
    - name: facebook
      url: "https://facebook.com/"
    - name: twitter
      url: "https://twitter.com/"
    - name: github
      url: "https://github.com/"

  cover: 
    linkFullImages: true
  
  ShowBreadCrumbs: true

  ShowReadingTime: true

  # ShowShareButtons: true

  ShowPostNavLinks: true



menu: 
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30