baseUrl: "https://clinquant-druid-c44612.netlify.app/"
languageCode: en-us
title: Brandshaw.cloud
theme: PaperMod
googleAnalytics: G-1234567890

params: 
  homeInfoParams:
    Title: "Hi I am John Bradshaw"
    Content: Head of Cloud Hub for @wpp, building out cloud for WPP and our OpCo’s in a customer obsessed way!
  socialIcons:
    - name: linkedin
      url: "https://facebook.com/"
    - name: twitter
      url: "https://twitter.com/"

  cover: 
    linkFullImages: true

  backgroundImage: img/waterbottle.jpg
  
  # ShowBreadCrumbs: true

  # ShowReadingTime: true

  ShowPostNavLinks: true



menu: 
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 10
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 20
    # - identifier: archives
    #   name: Archives
    #   url: /archives/
    #   weight: 30